### ISSUE TITLE
Not sure where to start

### ISSUE THREAD

**Issue by psntr** [bnomei/kirby3-boost#3]
Thanks for this new plugin.

I'm eager to make it work with a new project that would handle on a single request a lot of pages. But I'm having trouble to simply use BoostID.

Maybe I'm confused with your other plugin AutoID which was really straightforward and easy to use. With BoostID I seem not able to create and ID out of the box by following your instruction [here](https://forum.getkirby.com/t/remember-this-caching-in-kirby/23705#content-cache-19).

I have installed:
- kirby3-boost
- kirby3-sqlite-cachedriver

I have the **config.php** with:
```
return [
    'smartypants' => true,
    'debug' => false,
    'bnomei.boost.cache' => ['type' => 'sqlite']
];
```

In my models folder I have the following file **article.php**:

```
class ArticlePage extends \Bnomei\BoostPage
{
}
```

and finally in the panel I have **article.yml**:
```
columns:
  - width: 2/3
    fields:
      boostid:
        type: boostid
      headline:
        type: writer
        marks:
          - italic
      text: fields/blocks
      source:
        type: textarea

  - width: 1/3
    sections:
      meta:
        type: fields
        fields:
          date:
            type: date
            time: false
            default: now
          category: tags/category
```
When in article.php I try to output the boostID nothing is return, also the article.txt doesn't register the boostID. Finally in the panel if I check the article, there is the following error:
`SQLite3Stmt::execute(): Unable to execute statement: UNIQUE constraint failed: cache.id`

Sorry for the long message, but maybe I don't understand how it differs from autoID where the ID was naturally register on the .txt file.
