### ISSUE TITLE
Structure items with BoostID

### ISSUE THREAD

**Issue by psntr** [bnomei/kirby3-boost#4]
Hello!

It's me again, after being able to transfer my project from autoID to BoostID, I wanted to know if BoostID is compatible with a structure object?

I'm trying to have a page where there is a structure called "Categories" with inner fields that contains a title and the BoostID, for exemple:
```
categories:
    type: structure
    translate: false
    columns:
      color:
        width: 1/4
      category:
        width: 3/4
    fields:
      category:
        label: Category
        type: text
      boostid: fields/boostid
```
This page is unlisted but still has a models page in order to use BoostID. Nevertheless, I'm not able to create the ID's via:
```
kirby()->impersonate('kirby');
site()->boost();
// or this
foreach(site()->index(true) as $page) {
   $page->boost();
}
```
Before I had autoID for each of the structure items and I could use the immutable ID's to retrieve the title of the category or change it without breaking all articles related to this category.

Would appreciate a hint or how to achieve that with structure object.
